# Generated by Django 6.0.1 on 2026-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nexusmods_url', models.CharField(max_length=200)),
                ('mods', models.IntegerField()),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_id', models.IntegerField(unique=True)),
                ('game_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('picture_url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contra', models.CharField(max_length=100)),
            ],
        ),
    ]
