# Generated by Django 6.0.1 on 2026-01-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexusRankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='super',
            field=models.BooleanField(default=False),
        ),
    ]
