# Generated by Django 6.0.1 on 2026-01-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NexusRankings', '0003_remove_usuario_contra_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='super',
        ),
    ]
